### ISSUE TITLE
Use controls without media, for streamed media?

### ISSUE THREAD

**Issue by CoDEmanX** [homerours/cordova-music-controls-plugin#11]
Is it possible to somehow create the controls and indicate the duration of a medium, without specifying a media file?

This would be useful for applications that stream media on demand. It would allow the user to seek to an arbitrary position and a callback would send the requested position to the server, which would in turn seek to that position in the local media file and stream from there on.

**Comment by homerours** [comment]
Hi, 
There is no need to specify a music file to the plugin. This plugin is only displaying a notification with 3 buttons (and some informations), he's not playing a media file.

On Android, the "MediaStyle" notifications allow up to 5 buttons into one notification. But there is no available "seek or progress bar" available for notifications. That's why I think that it would be difficult to have one.

I think that you have to handle this "seek operations" inside of your app (and not in a notification). If a user wants to seek to an arbitrary position, he would have to go back to the app (by clicking on the notification, for instance) and seek using a html/js music player inside of the app.

Did I answer your question?
