### ISSUE TITLE
Problem with app when it is closed

### ISSUE THREAD

**Issue by portuga86** [homerours/cordova-music-controls-plugin#12]
When you close the app and reopen, a new control is created in the notification bar.
How to destroy the control before exit the app, or destroy when open it?

![captura de tela de 2015-10-08 09 20 59](https://cloud.githubusercontent.com/assets/10171818/10366020/eef1b662-6d9d-11e5-8e8d-0b59969cfb83.png)

**Comment by homerours** [comment]
Thanks for repporting this!
On android, all notifications are registered using aa notification id (an integer). For the moment, the plugin uses aa random id to register the notification: when you stop the app and reopen it, a new id will be chosen and the new notification don't override the older one. À quick fix would be to use a fix notification id, so that you would have at most 1 notification. 
I'll fix it in the next days. 
On my android 4.4, the notification disappear when I close the app. I'll investigate the 5.1 case

**Comment by homerours** [comment]
I fixed it ;)

**Comment by portuga86** [comment]
Thank you so much homerours!
=)
