### ISSUE TITLE
Notification not showing on Samsung Experience 9+

### ISSUE THREAD

**Issue by manelalonso** [homerours/cordova-music-controls-plugin#122]
Hello there,
Since i updated to the new version of Samsung Experience 9 (On Android 8.0) the notification is not appearing anymore, and it worked before the update. I noticed they reworked a bit the notification system on this update.

Is there any workaround to make it work? I'm using the default example code.

Thanks.

**Comment by triumvirat-FFDV** [comment]
Hello.
I had the same problem of you since I have the samsung s8+  phone. My problem was resolved going there => https://github.com/homerours/cordova-music-controls-plugin/issues/101, look the comment " commented on 16 Nov 2017" : 
You will need to downgrade your cordova-android to 6.2.3 ( **my cordova version last was  6.3.0**)
You will then need:
cordova-plugin-media at version 3.0.1
cordova-plugin-file at version 4.3.3
cordova-plugin-file-transfer at version 1.6.3
according to @AshishMehra.

**Comment by manelalonso** [comment]
I solved my problem with this: https://github.com/amitkhare/cordova-music-controls-plugin/blob/master/src/android/MusicControlsNotification.java
