### ISSUE TITLE
How to update notification?

### ISSUE THREAD

**Issue by remcova** [homerours/cordova-music-controls-plugin#35]
If I skip a song it doesn't update the notification with the correct info, is there an update/modify function available to edit the notification/music player?

**Comment by djmMax** [comment]
@remcova Destroy and Create new notification with new data

**Comment by filerun** [comment]
It would be more elegant to have a method like ``MusicControls.updateTrack('Some` track title');``

**Comment by filerun** [comment]
It would be great if there would be a function, to avoid the notification from jumping on recreate.

**Comment by homerours** [comment]
Hello,
This issue was discussed [in this PR](https://github.com/homerours/cordova-music-controls-plugin/pull/15). It is difficult to find a solution that keeps compatibility with android 4.1. It would be great to have one, you can have a look at the PR ...
You do not need to destroy, just call `create` again, this should update the notification.
