### ISSUE TITLE
stopped when app in background 

### ISSUE THREAD

**Issue by mrqaidi** [homerours/cordova-music-controls-plugin#69]
Hi

i am using shoutcast  mp3 url as media  and its playing fine in app  but when app in background and  controls showing in   toolbar  after certain seconds player get stopped

**Comment by CVeniamin** [comment]
In which platform do you have this issue?

**Comment by BuddyLReno** [comment]
Closing this issue since there's been no movement.  For iOS, if you need the audio in the background, You need to add the Background Mode capability for the app and check the Audio, AirPlay, and Picture-In-Picture checkbox.

![image](https://user-images.githubusercontent.com/1429547/32553897-b9b10ff2-c45d-11e7-91d0-ce38a66e83c9.png)
